### PR TITLE
Upgrade to Swift 3 (works with Xcode 8 beta 6)

### PR DESCRIPTION
**Pull request by robbiet480**
All done with the Xcode migration tool.

### CODE REVIEW

**Comment by volbap** [comment]
@robbiet480 thanks for the collaboration. We'll be reviewing and testing soon.

**Review by volbap — COMMENTED** [review]
@andresinaka this is approved. 👍 I tested it integrated with [Otec](https://github.com/inaka/Otec) and it works. Now, let's discuss a strategy on how to update these changes properly.

**Comment by volbap** [comment]
@robbiet480 we need you to fix the Travis CI check, which is failing, in order to merge. This is a `.travis.yml` file that works: https://github.com/andresinaka/SnapTimer/blob/master/.travis.yml
I suggest you to just copy-paste that version and change the target name with `EventSource`.

**Comment by robbiet480** [comment]
@volbap Change made, let's see what happens.

**Comment by andresinaka** [comment]
@robbiet480 thanks for the help! I think travis worked fine but there seems to be a failing test:

```
Failing tests:
    -[ConfigurationTests testEventsList()]
```

I don't have much time right now but i'll take a look as soon as I have some time to spare!

**Comment by robbiet480** [comment]
@andresinaka The test was fixed by reversing `first` and `second`. Not sure what changed in Swift 3, but I assume that initializing an Array in Swift 2.x would sort it?

**Comment by volbap** [comment]
@robbiet480 the test needs to be fixed. By definition:

> A `Dictionary` stores associations between keys of the same type and values of the same type in an collection **with no defined ordering**.

So, there's no guarantee that `eventListeners` will contain `first` and then `second` as keys, or the other way around. The test should check that they are just there, not their order.

cc @andresinaka

**Comment by andresinaka** [comment]
@volbap @robbiet480 that's true, we just need to check if the values are there not the order. Good catch, my first test was not very accurate 🙈... 

What do you think of using the .contains? with an XCTAssertTrue?

```
let elements = [1,2,3,4,5]
if elements.contains(5) {
    print("yes")
}
```

**Comment by robbiet480** [comment]
@andresinaka That looks like a good fix to me. I enabled edits on this PR from maintainers so that you can make the changes yourself. If you can't I can try to get to it tonight but i'm going to be busy most of today.

**Comment by volbap** [comment]
@robbiet480 thank you very much. We'll add whatever we need to get the PR merged, don't worry.

**Comment by andresinaka** [comment]
@robbiet480 thanks dude! 👊👊

**Comment by volbap** [comment]
@robbiet480 we integrated your commits 🎉 They've been merged in [this other pull request](https://github.com/inaka/EventSource/pull/63) due to merge conflicts and complications. Thanks for your collaboration.

**Comment by robbiet480** [comment]
Thanks! 🐬 🍪 💯

**Pull request closed without merging**
